.TH LIFEREA 1 "June 11, 2004" 
.SH NAME
Liferea \- RSS/RDF and Atom news aggregator
.SH SYNOPSIS
A short usage summary for Liferea.
.SH DESCRIPTION
\fBLiferea\fP (Linux Feed Reader) is an RSS/RDF and Atom news aggregator which also supports CDF channels, OCS, and OPML directories.
It's intended to be a clone of the Windows-only FeedReader.
It can be used to maintain a list of subscribed feeds, browse and search through their items, and displays their contents using GtkHTML or Mozilla.
.SH OPTIONS
Liferea options:
.TP
.B \-\-version
output version information and exit
.TP
.B \-\-help
display a option overview and exit
.TP
.B \-\-debug\-cache
Print debugging messages for the cache handling
.TP
.B \-\-debug\-conf
Print debugging messages of the configuration handling
.TP
.B \-\-debug\-update
Print debugging messages of the feed update processing
.TP
.B \-\-debug\-parsing
Print debugging messages of all parsing functions
.TP
.B \-\-debug\-gui
Print debugging messages of all GUI functions
.TP
.B \-\-debug\-trace
Print debugging messages when entering/leaving functions
.TP
.B \-\-debug\-all
Print debugging messages of all types
.TP
.B \-\-debug\-verbose
Print verbose debugging messages
.SH FILES
.I ~/.liferea/feedlist.opml
.I ~/.liferea/cache/feeds
.I ~/.liferea/cache/favicons
.I ~/.liferea/mozilla
.SH AUTHOR
This manual page was written by Lars Lindner <lars.lindner@gmx.net>.
