/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "fl_opml-cb.h"
#include "fl_opml-ui.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_instance_dialog (void)
{
  GtkWidget *instance_dialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *hbox1;
  GtkWidget *label2;
  GtkWidget *location_entry;
  GtkWidget *select_button;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  instance_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (instance_dialog), _("Add OPML/Planet"));
  gtk_window_set_type_hint (GTK_WINDOW (instance_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (instance_dialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 12);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 12);

  label1 = gtk_label_new (_("Please specify a local file or an URL pointing to a valid OPML feed list."));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_label_set_ellipsize (GTK_LABEL (label1), PANGO_ELLIPSIZE_START);

  hbox1 = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);

  label2 = gtk_label_new_with_mnemonic (_("_Location"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  location_entry = gtk_entry_new ();
  gtk_widget_show (location_entry);
  gtk_box_pack_start (GTK_BOX (hbox1), location_entry, TRUE, TRUE, 0);

  select_button = gtk_button_new_with_mnemonic (_("_Select File"));
  gtk_widget_show (select_button);
  gtk_box_pack_start (GTK_BOX (hbox1), select_button, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (instance_dialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (instance_dialog), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (instance_dialog), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label2), location_entry);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (instance_dialog, instance_dialog, "instance_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (instance_dialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (instance_dialog, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (instance_dialog, label1, "label1");
  GLADE_HOOKUP_OBJECT (instance_dialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (instance_dialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (instance_dialog, location_entry, "location_entry");
  GLADE_HOOKUP_OBJECT (instance_dialog, select_button, "select_button");
  GLADE_HOOKUP_OBJECT_NO_REF (instance_dialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (instance_dialog, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (instance_dialog, okbutton1, "okbutton1");

  return instance_dialog;
}

