/* batchfeedproperty.h generated by valac 0.26.1, the Vala compiler, do not modify */


#ifndef __BATCHFEEDPROPERTY_H__
#define __BATCHFEEDPROPERTY_H__

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>

G_BEGIN_DECLS


#define TYPE_BATCH_FEED_PROPERTY (batch_feed_property_get_type ())
#define BATCH_FEED_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_BATCH_FEED_PROPERTY, BatchFeedProperty))
#define BATCH_FEED_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_BATCH_FEED_PROPERTY, BatchFeedPropertyClass))
#define IS_BATCH_FEED_PROPERTY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_BATCH_FEED_PROPERTY))
#define IS_BATCH_FEED_PROPERTY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_BATCH_FEED_PROPERTY))
#define BATCH_FEED_PROPERTY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_BATCH_FEED_PROPERTY, BatchFeedPropertyClass))

typedef struct _BatchFeedProperty BatchFeedProperty;
typedef struct _BatchFeedPropertyClass BatchFeedPropertyClass;
typedef struct _BatchFeedPropertyPrivate BatchFeedPropertyPrivate;

struct _BatchFeedProperty {
	GObject parent_instance;
	BatchFeedPropertyPrivate * priv;
};

struct _BatchFeedPropertyClass {
	GObjectClass parent_class;
};


GType batch_feed_property_get_type (void) G_GNUC_CONST;
BatchFeedProperty* batch_feed_property_new (GtkWindow* parent);
BatchFeedProperty* batch_feed_property_construct (GType object_type, GtkWindow* parent);

void batch_feed_property_run (BatchFeedProperty* self);
void on_menu_batch_feed_property_change (GtkMenuItem *menuitem, gpointer user_data);

/**
 * Callbacks
 */
void on_batch_feed_property_changed (GtkWidget* wid, gpointer user_data);
void on_batch_feed_property_select_source_file(GtkWidget *wid, gpointer user_data);
void on_batch_feed_property_select_filter_file(GtkWidget *wid, gpointer user_data);

G_END_DECLS

#endif
