/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkWidget *refreshbtn;
  GtkWidget *prefbtn;
  GtkWidget *searchbtn;
  GtkWidget *helpbtn;
  GtkWidget *exitbtn;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow3;
  GtkWidget *feedlist;
  GtkWidget *vbox11;
  GtkWidget *searchbox;
  GtkWidget *label21;
  GtkWidget *searchentry;
  GtkWidget *hidesearch;
  GtkWidget *rightpane;
  GtkWidget *scrolledwindow5;
  GtkWidget *Itemlist;
  GtkWidget *statusbar;

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("Liferea 0.3.5"));
  gtk_window_set_default_size (GTK_WINDOW (mainwindow), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  refreshbtn = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-refresh",
                                "gtk-refresh",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (refreshbtn);

  prefbtn = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-preferences",
                                "gtk-preferences",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (prefbtn);

  searchbtn = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-find",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_show (searchbtn);

  helpbtn = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-help",
                                "gtk-help",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (helpbtn);

  exitbtn = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-quit",
                                "gtk-quit",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (exitbtn);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 170);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow3, FALSE, FALSE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  feedlist = gtk_tree_view_new ();
  gtk_widget_show (feedlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), feedlist);
  gtk_widget_set_size_request (feedlist, 150, -1);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (feedlist), FALSE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (feedlist), TRUE);

  vbox11 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox11);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vbox11, TRUE, TRUE);

  searchbox = gtk_hbox_new (FALSE, 5);
  gtk_box_pack_start (GTK_BOX (vbox11), searchbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (searchbox), 5);

  label21 = gtk_label_new (_("search for"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (searchbox), label21, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);

  searchentry = gtk_entry_new ();
  gtk_widget_show (searchentry);
  gtk_box_pack_start (GTK_BOX (searchbox), searchentry, TRUE, TRUE, 0);

  hidesearch = gtk_button_new_with_mnemonic (_("X"));
  gtk_widget_show (hidesearch);
  gtk_box_pack_start (GTK_BOX (searchbox), hidesearch, FALSE, FALSE, 0);

  rightpane = gtk_vpaned_new ();
  gtk_widget_show (rightpane);
  gtk_box_pack_start (GTK_BOX (vbox11), rightpane, TRUE, TRUE, 0);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_paned_pack1 (GTK_PANED (rightpane), scrolledwindow5, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  Itemlist = gtk_tree_view_new ();
  gtk_widget_show (Itemlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), Itemlist);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (Itemlist), TRUE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect_swapped ((gpointer) refreshbtn, "clicked",
                            G_CALLBACK (on_refreshbtn_clicked),
                            GTK_OBJECT (feedlist));
  g_signal_connect ((gpointer) prefbtn, "clicked",
                    G_CALLBACK (on_prefbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) searchbtn, "clicked",
                    G_CALLBACK (on_searchbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) helpbtn, "clicked",
                    G_CALLBACK (on_helpbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) exitbtn, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) feedlist, "button_press_event",
                    G_CALLBACK (on_mainfeedlist_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) searchentry, "activate",
                    G_CALLBACK (on_searchentry_activate),
                    NULL);
  g_signal_connect ((gpointer) hidesearch, "clicked",
                    G_CALLBACK (on_hidesearch_clicked),
                    NULL);
  g_signal_connect ((gpointer) Itemlist, "button_press_event",
                    G_CALLBACK (on_itemlist_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainwindow, refreshbtn, "refreshbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, prefbtn, "prefbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, searchbtn, "searchbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, helpbtn, "helpbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, exitbtn, "exitbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (mainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (mainwindow, feedlist, "feedlist");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (mainwindow, searchbox, "searchbox");
  GLADE_HOOKUP_OBJECT (mainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (mainwindow, searchentry, "searchentry");
  GLADE_HOOKUP_OBJECT (mainwindow, hidesearch, "hidesearch");
  GLADE_HOOKUP_OBJECT (mainwindow, rightpane, "rightpane");
  GLADE_HOOKUP_OBJECT (mainwindow, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (mainwindow, Itemlist, "Itemlist");
  GLADE_HOOKUP_OBJECT (mainwindow, statusbar, "statusbar");

  gtk_widget_grab_focus (feedlist);
  return mainwindow;
}

GtkWidget*
create_propdialog (void)
{
  GtkWidget *propdialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox7;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *feednameentry;
  GtkWidget *feedurlentry;
  GtkWidget *label3;
  GtkWidget *frame4;
  GtkWidget *vbox8;
  GtkWidget *hbox8;
  GtkWidget *label18;
  GtkObject *feedrefreshcount_adj;
  GtkWidget *feedrefreshcount;
  GtkWidget *feedupdateinfo;
  GtkWidget *label19;
  GtkWidget *dialog_action_area1;
  GtkWidget *propchangebtn;
  GtkWidget *cancelbtn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  propdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (propdialog), _("Properties"));
  gtk_window_set_position (GTK_WINDOW (propdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (propdialog), 400, -1);

  dialog_vbox1 = GTK_DIALOG (propdialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox7, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox7), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  label2 = gtk_label_new (_("feed name"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  feednameentry = gtk_entry_new ();
  gtk_widget_show (feednameentry);
  gtk_table_attach (GTK_TABLE (table1), feednameentry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, feednameentry, _("either leave the name supplied by the feed or enter an alternative name which you like to be listed in the feed list"), NULL);
  gtk_entry_set_text (GTK_ENTRY (feednameentry), _("\t\tif(0 == interval)\n\t\t\tinterval = -1;\t/* this is due to ignore this feed while updating */"));

  feedurlentry = gtk_entry_new ();
  gtk_widget_show (feedurlentry);
  gtk_table_attach (GTK_TABLE (table1), feedurlentry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, feedurlentry, _("enter the URL the feed should be loaded from"), NULL);

  label3 = gtk_label_new (_("feed URL"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox7), frame4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  vbox8 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame4), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 5);

  hbox8 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 5);

  label18 = gtk_label_new (_("feed refresh interval (in minutes)"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  feedrefreshcount_adj = gtk_adjustment_new (0, 0, 100000, 5, 10, 10);
  feedrefreshcount = gtk_spin_button_new (GTK_ADJUSTMENT (feedrefreshcount_adj), 1, 0);
  gtk_widget_show (feedrefreshcount);
  gtk_box_pack_start (GTK_BOX (hbox8), feedrefreshcount, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feedrefreshcount, _("Please remember to set a reasonable refresh time, its not useful to poll daily updated feeds every 15 minutes! To disable auto-updating the feed set the interval to 0."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (feedrefreshcount), TRUE);

  feedupdateinfo = gtk_label_new ("");
  gtk_widget_show (feedupdateinfo);
  gtk_box_pack_start (GTK_BOX (vbox8), feedupdateinfo, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (feedupdateinfo), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (feedupdateinfo), 0, 0.5);

  label19 = gtk_label_new (_("update interval"));
  gtk_widget_show (label19);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label19), 5, 0);

  dialog_action_area1 = GTK_DIALOG (propdialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  propchangebtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (propchangebtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (propdialog), propchangebtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (propchangebtn, GTK_CAN_DEFAULT);

  cancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (propdialog), cancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) propdialog, "close",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (propdialog));
  g_signal_connect_data ((gpointer) propchangebtn, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (propdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect ((gpointer) propchangebtn, "clicked",
                    G_CALLBACK (on_propchangebtn_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (propdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, propdialog, "propdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (propdialog, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (propdialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (propdialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (propdialog, feednameentry, "feednameentry");
  GLADE_HOOKUP_OBJECT (propdialog, feedurlentry, "feedurlentry");
  GLADE_HOOKUP_OBJECT (propdialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (propdialog, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (propdialog, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (propdialog, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (propdialog, label18, "label18");
  GLADE_HOOKUP_OBJECT (propdialog, feedrefreshcount, "feedrefreshcount");
  GLADE_HOOKUP_OBJECT (propdialog, feedupdateinfo, "feedupdateinfo");
  GLADE_HOOKUP_OBJECT (propdialog, label19, "label19");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (propdialog, propchangebtn, "propchangebtn");
  GLADE_HOOKUP_OBJECT (propdialog, cancelbtn, "cancelbtn");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, tooltips, "tooltips");

  return propdialog;
}

GtkWidget*
create_newdialog (void)
{
  GtkWidget *newdialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox9;
  GtkWidget *hbox1;
  GtkWidget *label5;
  GtkWidget *newfeedentry;
  GtkWidget *hbox11;
  GtkWidget *typeradiobtn;
  GSList *typeradiobtn_group = NULL;
  GtkWidget *typeradiobutton1;
  GtkWidget *typeradiobtn2;
  GtkWidget *dialog_action_area2;
  GtkWidget *newfeedbtn;
  GtkWidget *cancelbtn;

  newdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (newdialog), _("New Entry"));
  gtk_window_set_position (GTK_WINDOW (newdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (newdialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (newdialog), 400, -1);

  dialog_vbox2 = GTK_DIALOG (newdialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox9, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  label5 = gtk_label_new (_("feed URL"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  newfeedentry = gtk_entry_new ();
  gtk_widget_show (newfeedentry);
  gtk_box_pack_start (GTK_BOX (hbox1), newfeedentry, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox11, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 5);

  typeradiobtn = gtk_radio_button_new_with_mnemonic (NULL, _("RSS Feed"));
  gtk_widget_show (typeradiobtn);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (typeradiobtn), TRUE);

  typeradiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("CDF Feed"));
  gtk_widget_show (typeradiobutton1);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobutton1), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobutton1));

  typeradiobtn2 = gtk_radio_button_new_with_mnemonic (NULL, _("OCS Directory"));
  gtk_widget_show (typeradiobtn2);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn2), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn2));

  dialog_action_area2 = GTK_DIALOG (newdialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  newfeedbtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (newfeedbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (newdialog), newfeedbtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (newfeedbtn, GTK_CAN_DEFAULT);

  cancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (newdialog), cancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) newfeedbtn, "clicked",
                            G_CALLBACK (on_newfeedbtn_clicked),
                            GTK_OBJECT (newfeedentry));
  g_signal_connect_data ((gpointer) newfeedbtn, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (newdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) cancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, newdialog, "newdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (newdialog, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (newdialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (newdialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (newdialog, newfeedentry, "newfeedentry");
  GLADE_HOOKUP_OBJECT (newdialog, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn, "typeradiobtn");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobutton1, "typeradiobutton1");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn2, "typeradiobtn2");
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (newdialog, newfeedbtn, "newfeedbtn");
  GLADE_HOOKUP_OBJECT (newdialog, cancelbtn, "cancelbtn");

  return newdialog;
}

GtkWidget*
create_feednamedialog (void)
{
  GtkWidget *feednamedialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox6;
  GtkWidget *hbox2;
  GtkWidget *feedname;
  GtkWidget *feednameentry;
  GtkWidget *hbox7;
  GtkWidget *label17;
  GtkObject *feedrefreshcount_adj;
  GtkWidget *feedrefreshcount;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton4;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  feednamedialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (feednamedialog), _("Entry Name"));
  gtk_window_set_position (GTK_WINDOW (feednamedialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (feednamedialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (feednamedialog), 400, -1);

  dialog_vbox4 = GTK_DIALOG (feednamedialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox6, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  feedname = gtk_label_new (_("feed name"));
  gtk_widget_show (feedname);
  gtk_box_pack_start (GTK_BOX (hbox2), feedname, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (feedname), GTK_JUSTIFY_LEFT);

  feednameentry = gtk_entry_new ();
  gtk_widget_show (feednameentry);
  gtk_box_pack_start (GTK_BOX (hbox2), feednameentry, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feednameentry, _("either leave the name supplied by the feed or enter an alternative name which you like to be listed in the feed list"), NULL);

  hbox7 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox7), 5);

  label17 = gtk_label_new (_("feed refresh interval (in minutes)"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  feedrefreshcount_adj = gtk_adjustment_new (0, 0, 100000, 5, 10, 10);
  feedrefreshcount = gtk_spin_button_new (GTK_ADJUSTMENT (feedrefreshcount_adj), 1, 0);
  gtk_widget_show (feedrefreshcount);
  gtk_box_pack_start (GTK_BOX (hbox7), feedrefreshcount, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feedrefreshcount, _("Please remember to set a reasonable refresh time, its not useful to poll daily updated feeds every 15 minutes! To disable auto-updating the feed set the interval to 0."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (feedrefreshcount), TRUE);

  dialog_action_area4 = GTK_DIALOG (feednamedialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (feednamedialog), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) okbutton4, "clicked",
                            G_CALLBACK (on_feednamebutton_clicked),
                            GTK_OBJECT (feednameentry));
  g_signal_connect_data ((gpointer) okbutton4, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (feednamedialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, feednamedialog, "feednamedialog");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (feednamedialog, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (feednamedialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (feednamedialog, feedname, "feedname");
  GLADE_HOOKUP_OBJECT (feednamedialog, feednameentry, "feednameentry");
  GLADE_HOOKUP_OBJECT (feednamedialog, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (feednamedialog, label17, "label17");
  GLADE_HOOKUP_OBJECT (feednamedialog, feedrefreshcount, "feedrefreshcount");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (feednamedialog, okbutton4, "okbutton4");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, tooltips, "tooltips");

  return feednamedialog;
}

GtkWidget*
create_prefdialog (void)
{
  GtkWidget *prefdialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox3;
  GtkWidget *frame2;
  GtkWidget *table4;
  GtkWidget *label7;
  GtkWidget *browsercmd;
  GtkWidget *label8;
  GtkWidget *timeformat;
  GtkWidget *label13;
  GtkWidget *frame3;
  GtkWidget *vbox5;
  GtkWidget *hbox6;
  GtkWidget *label15;
  GtkWidget *usedc;
  GtkWidget *usecontent;
  GtkWidget *useslash;
  GtkWidget *hbox9;
  GtkWidget *usefm;
  GtkWidget *usesyn;
  GtkWidget *usesy;
  GtkWidget *useadmin;
  GtkWidget *label16;
  GtkWidget *label14;
  GtkWidget *frame1;
  GtkWidget *vbox4;
  GtkWidget *useproxy;
  GtkWidget *table3;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *proxyhost;
  GtkWidget *proxyport;
  GtkWidget *label12;
  GtkWidget *dialog_action_area5;
  GtkWidget *prefsavebtn;
  GtkWidget *prefcancelbtn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  prefdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prefdialog), _("program preferences"));
  gtk_window_set_position (GTK_WINDOW (prefdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (prefdialog), 300, -1);

  dialog_vbox5 = GTK_DIALOG (prefdialog)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox3, FALSE, TRUE, 2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, TRUE, TRUE, 0);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame2), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 5);

  label7 = gtk_label_new (_("browser command"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table4), label7, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  browsercmd = gtk_entry_new ();
  gtk_widget_show (browsercmd);
  gtk_table_attach (GTK_TABLE (table4), browsercmd, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, browsercmd, _("specify a browser command using %s as URL placeholder"), NULL);
  gtk_entry_set_text (GTK_ENTRY (browsercmd), _("http://news.synearth.net/xml/scriptingnews2.xml"));

  label8 = gtk_label_new (_("time format string\nwhich is used for\nthe date column"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table4), label8, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  timeformat = gtk_entry_new ();
  gtk_widget_show (timeformat);
  gtk_table_attach (GTK_TABLE (table4), timeformat, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, timeformat, _("specify a string with a formatstring as used with the date command (e.g. %H:%M %d.%m.)"), NULL);

  label13 = gtk_label_new (_("program options"));
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label13);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label13), 5, 0);

  frame3 = gtk_frame_new (NULL);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox3), frame3, TRUE, TRUE, 1);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame3), vbox5);

  hbox6 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox6), 5);

  label15 = gtk_label_new (_("enable RSS module"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox6), label15, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_LEFT);

  usedc = gtk_check_button_new_with_mnemonic (_("dc"));
  gtk_widget_show (usedc);
  gtk_box_pack_start (GTK_BOX (hbox6), usedc, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, usedc, _("enable Dublin Core support"), NULL);

  usecontent = gtk_check_button_new_with_mnemonic (_("content"));
  gtk_widget_show (usecontent);
  gtk_box_pack_start (GTK_BOX (hbox6), usecontent, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, usecontent, _("enable encoded content support"), NULL);

  useslash = gtk_check_button_new_with_mnemonic (_("slash"));
  gtk_widget_show (useslash);
  gtk_box_pack_start (GTK_BOX (hbox6), useslash, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, useslash, _("enable slashdot support"), NULL);

  hbox9 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox9, FALSE, FALSE, 0);

  usefm = gtk_check_button_new_with_mnemonic (_("fm"));
  gtk_widget_show (usefm);
  gtk_box_pack_start (GTK_BOX (hbox9), usefm, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, usefm, _("enable the freshmeat namespace (this will enable the freshmeat screenshots)"), NULL);

  usesyn = gtk_check_button_new_with_mnemonic (_("syn"));
  gtk_widget_show (usesyn);
  gtk_box_pack_start (GTK_BOX (hbox9), usesyn, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (usesyn, FALSE);

  usesy = gtk_check_button_new_with_mnemonic (_("sy"));
  gtk_widget_show (usesy);
  gtk_box_pack_start (GTK_BOX (hbox9), usesy, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (usesy, FALSE);

  useadmin = gtk_check_button_new_with_mnemonic (_("admin"));
  gtk_widget_show (useadmin);
  gtk_box_pack_start (GTK_BOX (hbox9), useadmin, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (useadmin, FALSE);

  label16 = gtk_label_new (_("(Note: you have to refresh feeds to load affected information after enabling a module)"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (vbox5), label16, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label16), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label16), 5, 0);

  label14 = gtk_label_new (_("parsing options"));
  gtk_widget_show (label14);
  gtk_frame_set_label_widget (GTK_FRAME (frame3), label14);
  gtk_label_set_justify (GTK_LABEL (label14), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label14), 5, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox3), frame1, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (frame1), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  useproxy = gtk_check_button_new_with_mnemonic (_("use proxy"));
  gtk_widget_show (useproxy);
  gtk_box_pack_start (GTK_BOX (vbox4), useproxy, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, useproxy, _("enable if you want to use a proxy (Note: by changing this setting you change the global gconf proxy setting, which might affect other programs!)"), NULL);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (useproxy), TRUE);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox4), table3, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 5);

  label10 = gtk_label_new (_("proxy host"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table3), label10, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label11 = gtk_label_new (_("proxy port"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table3), label11, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  proxyhost = gtk_entry_new ();
  gtk_widget_show (proxyhost);
  gtk_table_attach (GTK_TABLE (table3), proxyhost, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, proxyhost, _("enter your proxy hostname or IP (Note: by changing this setting you change the global gconf proxy setting, which might affect other programs!)"), NULL);

  proxyport = gtk_entry_new ();
  gtk_widget_show (proxyport);
  gtk_table_attach (GTK_TABLE (table3), proxyport, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, proxyport, _("enter your proxy port number (Note: by changing this setting you change the global gconf proxy setting, which might affect other programs!)"), NULL);

  label12 = gtk_label_new (_("system proxy settings"));
  gtk_widget_show (label12);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label12);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label12), 5, 0);

  dialog_action_area5 = GTK_DIALOG (prefdialog)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  prefsavebtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (prefsavebtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdialog), prefsavebtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (prefsavebtn, GTK_CAN_DEFAULT);

  prefcancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (prefcancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdialog), prefcancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (prefcancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) prefsavebtn, "clicked",
                    G_CALLBACK (on_prefsavebtn_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) prefcancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (prefdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, prefdialog, "prefdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (prefdialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (prefdialog, table4, "table4");
  GLADE_HOOKUP_OBJECT (prefdialog, label7, "label7");
  GLADE_HOOKUP_OBJECT (prefdialog, browsercmd, "browsercmd");
  GLADE_HOOKUP_OBJECT (prefdialog, label8, "label8");
  GLADE_HOOKUP_OBJECT (prefdialog, timeformat, "timeformat");
  GLADE_HOOKUP_OBJECT (prefdialog, label13, "label13");
  GLADE_HOOKUP_OBJECT (prefdialog, frame3, "frame3");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (prefdialog, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (prefdialog, label15, "label15");
  GLADE_HOOKUP_OBJECT (prefdialog, usedc, "usedc");
  GLADE_HOOKUP_OBJECT (prefdialog, usecontent, "usecontent");
  GLADE_HOOKUP_OBJECT (prefdialog, useslash, "useslash");
  GLADE_HOOKUP_OBJECT (prefdialog, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (prefdialog, usefm, "usefm");
  GLADE_HOOKUP_OBJECT (prefdialog, usesyn, "usesyn");
  GLADE_HOOKUP_OBJECT (prefdialog, usesy, "usesy");
  GLADE_HOOKUP_OBJECT (prefdialog, useadmin, "useadmin");
  GLADE_HOOKUP_OBJECT (prefdialog, label16, "label16");
  GLADE_HOOKUP_OBJECT (prefdialog, label14, "label14");
  GLADE_HOOKUP_OBJECT (prefdialog, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (prefdialog, useproxy, "useproxy");
  GLADE_HOOKUP_OBJECT (prefdialog, table3, "table3");
  GLADE_HOOKUP_OBJECT (prefdialog, label10, "label10");
  GLADE_HOOKUP_OBJECT (prefdialog, label11, "label11");
  GLADE_HOOKUP_OBJECT (prefdialog, proxyhost, "proxyhost");
  GLADE_HOOKUP_OBJECT (prefdialog, proxyport, "proxyport");
  GLADE_HOOKUP_OBJECT (prefdialog, label12, "label12");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (prefdialog, prefsavebtn, "prefsavebtn");
  GLADE_HOOKUP_OBJECT (prefdialog, prefcancelbtn, "prefcancelbtn");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, tooltips, "tooltips");

  return prefdialog;
}

GtkWidget*
create_newfolderdialog (void)
{
  GtkWidget *newfolderdialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox10;
  GtkWidget *hbox12;
  GtkWidget *label20;
  GtkWidget *foldertitleentry;
  GtkWidget *dialog_action_area6;
  GtkWidget *button2;
  GtkWidget *button3;

  newfolderdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (newfolderdialog), _("add folder"));
  gtk_window_set_modal (GTK_WINDOW (newfolderdialog), TRUE);

  dialog_vbox6 = GTK_DIALOG (newfolderdialog)->vbox;
  gtk_widget_show (dialog_vbox6);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox10, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox12, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox12), 5);

  label20 = gtk_label_new (_("folder name"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox12), label20, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);

  foldertitleentry = gtk_entry_new ();
  gtk_widget_show (foldertitleentry);
  gtk_box_pack_start (GTK_BOX (hbox12), foldertitleentry, TRUE, TRUE, 0);

  dialog_action_area6 = GTK_DIALOG (newfolderdialog)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (newfolderdialog), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (newfolderdialog), button3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_newfolderbtn_clicked),
                    NULL);
  g_signal_connect_data ((gpointer) button2, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (newfolderdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newfolderdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, newfolderdialog, "newfolderdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (newfolderdialog, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (newfolderdialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (newfolderdialog, label20, "label20");
  GLADE_HOOKUP_OBJECT (newfolderdialog, foldertitleentry, "foldertitleentry");
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (newfolderdialog, button2, "button2");
  GLADE_HOOKUP_OBJECT (newfolderdialog, button3, "button3");

  return newfolderdialog;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *rightpane;
  GtkWidget *scrolledwindow4;
  GtkWidget *Itemlist;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  rightpane = gtk_vpaned_new ();
  gtk_widget_show (rightpane);
  gtk_container_add (GTK_CONTAINER (window1), rightpane);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_paned_pack1 (GTK_PANED (rightpane), scrolledwindow4, TRUE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  Itemlist = gtk_tree_view_new ();
  gtk_widget_show (Itemlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), Itemlist);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (Itemlist), TRUE);

  g_signal_connect ((gpointer) Itemlist, "button_press_event",
                    G_CALLBACK (on_itemlist_button_press_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, rightpane, "rightpane");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (window1, Itemlist, "Itemlist");

  return window1;
}

