/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_propdialog (void);
GtkWidget* create_newdialog (void);
GtkWidget* create_prefdialog (void);
GtkWidget* create_newfolderdialog (void);
GtkWidget* create_nodenamedialog (void);
GtkWidget* create_searchenginedialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_authdialog (void);
GtkWidget* create_vfolderdialog (void);
GtkWidget* create_enchandlerdialog (void);
GtkWidget* create_searchdialog (void);
GtkWidget* create_updatedialog (void);
GtkWidget* create_simplenewdialog (void);
GtkWidget* create_scriptdialog (void);
GtkWidget* create_scriptadddialog (void);
GtkWidget* create_newnewsbindialog (void);
