/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkWidget *refreshbtn;
  GtkWidget *alignment1;
  GtkWidget *hbox16;
  GtkWidget *image2;
  GtkWidget *label24;
  GtkWidget *searchbtn;
  GtkWidget *alignment2;
  GtkWidget *hbox17;
  GtkWidget *image3;
  GtkWidget *label25;
  GtkWidget *prefbtn;
  GtkWidget *hpaned1;
  GtkWidget *scrolledwindow3;
  GtkWidget *feedlist;
  GtkWidget *rightpane;
  GtkWidget *vbox13;
  GtkWidget *searchbox;
  GtkWidget *label21;
  GtkWidget *searchentry;
  GtkWidget *newVFolder;
  GtkWidget *hidesearch;
  GtkWidget *image1;
  GtkWidget *ilscrolledwindow;
  GtkWidget *Itemlist;
  GtkWidget *statusbar;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("Liferea 0.3.8"));
  gtk_window_set_default_size (GTK_WINDOW (mainwindow), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (toolbar1), 1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);

  refreshbtn = gtk_button_new ();
  gtk_widget_show (refreshbtn);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), refreshbtn, _("Update feeds"), NULL);
  GTK_WIDGET_UNSET_FLAGS (refreshbtn, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (refreshbtn), GTK_RELIEF_NONE);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (refreshbtn), alignment1);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox16);

  image2 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox16), image2, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Update"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox16), label24, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);

  searchbtn = gtk_button_new ();
  gtk_widget_show (searchbtn);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), searchbtn, _("Search in feeds"), NULL);
  GTK_WIDGET_UNSET_FLAGS (searchbtn, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (searchbtn), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (searchbtn), alignment2);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox17);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox17), image3, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Search"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox17), label25, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);

  prefbtn = gtk_button_new_from_stock ("gtk-preferences");
  gtk_widget_show (prefbtn);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), prefbtn, _("Edit preferences"), NULL);
  GTK_WIDGET_UNSET_FLAGS (prefbtn, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (prefbtn), GTK_RELIEF_NONE);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 170);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_paned_pack1 (GTK_PANED (hpaned1), scrolledwindow3, FALSE, TRUE);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  feedlist = gtk_tree_view_new ();
  gtk_widget_show (feedlist);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), feedlist);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (feedlist), FALSE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (feedlist), TRUE);

  rightpane = gtk_vpaned_new ();
  gtk_widget_show (rightpane);
  gtk_paned_pack2 (GTK_PANED (hpaned1), rightpane, FALSE, TRUE);
  gtk_paned_set_position (GTK_PANED (rightpane), 200);

  vbox13 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox13);
  gtk_paned_pack1 (GTK_PANED (rightpane), vbox13, FALSE, TRUE);

  searchbox = gtk_hbox_new (FALSE, 5);
  gtk_box_pack_start (GTK_BOX (vbox13), searchbox, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (searchbox), 5);

  label21 = gtk_label_new (_("Search for"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (searchbox), label21, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);

  searchentry = gtk_entry_new ();
  gtk_widget_show (searchentry);
  gtk_box_pack_start (GTK_BOX (searchbox), searchentry, TRUE, TRUE, 0);

  newVFolder = gtk_button_new_with_mnemonic (_("create VFolder"));
  gtk_box_pack_start (GTK_BOX (searchbox), newVFolder, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, newVFolder, _("saves this search as a VFolder, which will appear in the feed list"), NULL);

  hidesearch = gtk_button_new ();
  gtk_widget_show (hidesearch);
  gtk_box_pack_start (GTK_BOX (searchbox), hidesearch, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, hidesearch, _("Close search"), NULL);
  gtk_button_set_relief (GTK_BUTTON (hidesearch), GTK_RELIEF_NONE);

  image1 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (hidesearch), image1);

  ilscrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (ilscrolledwindow);
  gtk_box_pack_start (GTK_BOX (vbox13), ilscrolledwindow, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (ilscrolledwindow), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

  Itemlist = gtk_tree_view_new ();
  gtk_widget_show (Itemlist);
  gtk_container_add (GTK_CONTAINER (ilscrolledwindow), Itemlist);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (Itemlist), TRUE);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) mainwindow, "delete_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect_swapped ((gpointer) refreshbtn, "clicked",
                            G_CALLBACK (on_refreshbtn_clicked),
                            GTK_OBJECT (feedlist));
  g_signal_connect ((gpointer) searchbtn, "clicked",
                    G_CALLBACK (on_searchbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) prefbtn, "clicked",
                    G_CALLBACK (on_prefbtn_clicked),
                    NULL);
  g_signal_connect ((gpointer) feedlist, "button_press_event",
                    G_CALLBACK (on_mainfeedlist_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) feedlist, "drag_begin",
                    G_CALLBACK (on_feedlist_drag_begin),
                    NULL);
  g_signal_connect ((gpointer) feedlist, "drag_end",
                    G_CALLBACK (on_feedlist_drag_end),
                    NULL);
  g_signal_connect ((gpointer) feedlist, "drag_drop",
                    G_CALLBACK (on_feedlist_drag_drop),
                    NULL);
  g_signal_connect ((gpointer) searchentry, "activate",
                    G_CALLBACK (on_searchentry_activate),
                    NULL);
  g_signal_connect ((gpointer) newVFolder, "clicked",
                    G_CALLBACK (on_newVFolder_clicked),
                    NULL);
  g_signal_connect ((gpointer) hidesearch, "clicked",
                    G_CALLBACK (on_hidesearch_clicked),
                    NULL);
  g_signal_connect_after ((gpointer) Itemlist, "move_cursor",
                          G_CALLBACK (on_Itemlist_move_cursor),
                          NULL);
  g_signal_connect ((gpointer) Itemlist, "button_press_event",
                    G_CALLBACK (on_itemlist_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) Itemlist, "row_activated",
                    G_CALLBACK (on_Itemlist_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainwindow, refreshbtn, "refreshbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (mainwindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (mainwindow, label24, "label24");
  GLADE_HOOKUP_OBJECT (mainwindow, searchbtn, "searchbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (mainwindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (mainwindow, label25, "label25");
  GLADE_HOOKUP_OBJECT (mainwindow, prefbtn, "prefbtn");
  GLADE_HOOKUP_OBJECT (mainwindow, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (mainwindow, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (mainwindow, feedlist, "feedlist");
  GLADE_HOOKUP_OBJECT (mainwindow, rightpane, "rightpane");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (mainwindow, searchbox, "searchbox");
  GLADE_HOOKUP_OBJECT (mainwindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (mainwindow, searchentry, "searchentry");
  GLADE_HOOKUP_OBJECT (mainwindow, newVFolder, "newVFolder");
  GLADE_HOOKUP_OBJECT (mainwindow, hidesearch, "hidesearch");
  GLADE_HOOKUP_OBJECT (mainwindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (mainwindow, ilscrolledwindow, "ilscrolledwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, Itemlist, "Itemlist");
  GLADE_HOOKUP_OBJECT (mainwindow, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, tooltips, "tooltips");

  gtk_widget_grab_focus (feedlist);
  return mainwindow;
}

GtkWidget*
create_propdialog (void)
{
  GtkWidget *propdialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox7;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *feednameentry;
  GtkWidget *feedurlentry;
  GtkWidget *label3;
  GtkWidget *frame4;
  GtkWidget *vbox8;
  GtkWidget *hbox8;
  GtkWidget *label18;
  GtkObject *feedrefreshcount_adj;
  GtkWidget *feedrefreshcount;
  GtkWidget *feedupdateinfo;
  GtkWidget *label19;
  GtkWidget *dialog_action_area1;
  GtkWidget *propchangebtn;
  GtkWidget *cancelbtn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  propdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (propdialog), _("Properties"));
  gtk_window_set_position (GTK_WINDOW (propdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (propdialog), 400, -1);

  dialog_vbox1 = GTK_DIALOG (propdialog)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox7, TRUE, TRUE, 0);

  table1 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox7), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  label2 = gtk_label_new (_("feed name"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  feednameentry = gtk_entry_new ();
  gtk_widget_show (feednameentry);
  gtk_table_attach (GTK_TABLE (table1), feednameentry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, feednameentry, _("either leave the name supplied by the feed or enter an alternative name which you like to be listed in the feed list"), NULL);
  gtk_entry_set_text (GTK_ENTRY (feednameentry), _("\t\tif(0 == interval)\n\t\t\tinterval = -1;\t/* this is due to ignore this feed while updating */"));

  feedurlentry = gtk_entry_new ();
  gtk_widget_show (feedurlentry);
  gtk_table_attach (GTK_TABLE (table1), feedurlentry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, feedurlentry, _("enter the URL the feed should be loaded from"), NULL);

  label3 = gtk_label_new (_("feed URL"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox7), frame4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame4), 5);

  vbox8 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame4), vbox8);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 5);

  hbox8 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox8, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox8), 5);

  label18 = gtk_label_new (_("feed refresh interval (in minutes)"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);

  feedrefreshcount_adj = gtk_adjustment_new (0, 0, 100000, 5, 10, 10);
  feedrefreshcount = gtk_spin_button_new (GTK_ADJUSTMENT (feedrefreshcount_adj), 1, 0);
  gtk_widget_show (feedrefreshcount);
  gtk_box_pack_start (GTK_BOX (hbox8), feedrefreshcount, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feedrefreshcount, _("Please remember to set a reasonable refresh time, its not useful to poll daily updated feeds every 15 minutes! To disable auto-updating the feed set the interval to 0."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (feedrefreshcount), TRUE);

  feedupdateinfo = gtk_label_new ("");
  gtk_widget_show (feedupdateinfo);
  gtk_box_pack_start (GTK_BOX (vbox8), feedupdateinfo, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (feedupdateinfo), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (feedupdateinfo), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (feedupdateinfo), 5, 0);

  label19 = gtk_label_new (_("update interval"));
  gtk_widget_show (label19);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label19);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label19), 5, 0);

  dialog_action_area1 = GTK_DIALOG (propdialog)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  propchangebtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (propchangebtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (propdialog), propchangebtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (propchangebtn, GTK_CAN_DEFAULT);

  cancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (propdialog), cancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) propdialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (propdialog));
  g_signal_connect_data ((gpointer) propchangebtn, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (propdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect ((gpointer) propchangebtn, "clicked",
                    G_CALLBACK (on_propchangebtn_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (propdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, propdialog, "propdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (propdialog, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (propdialog, table1, "table1");
  GLADE_HOOKUP_OBJECT (propdialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (propdialog, feednameentry, "feednameentry");
  GLADE_HOOKUP_OBJECT (propdialog, feedurlentry, "feedurlentry");
  GLADE_HOOKUP_OBJECT (propdialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (propdialog, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (propdialog, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (propdialog, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (propdialog, label18, "label18");
  GLADE_HOOKUP_OBJECT (propdialog, feedrefreshcount, "feedrefreshcount");
  GLADE_HOOKUP_OBJECT (propdialog, feedupdateinfo, "feedupdateinfo");
  GLADE_HOOKUP_OBJECT (propdialog, label19, "label19");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (propdialog, propchangebtn, "propchangebtn");
  GLADE_HOOKUP_OBJECT (propdialog, cancelbtn, "cancelbtn");
  GLADE_HOOKUP_OBJECT_NO_REF (propdialog, tooltips, "tooltips");

  return propdialog;
}

GtkWidget*
create_newdialog (void)
{
  GtkWidget *newdialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox9;
  GtkWidget *hbox1;
  GtkWidget *label5;
  GtkWidget *newfeedentry;
  GtkWidget *vbox12;
  GtkWidget *frame5;
  GtkWidget *hbox11;
  GtkWidget *typeradiobtn;
  GSList *typeradiobtn_group = NULL;
  GtkWidget *typeradiobtn1;
  GtkWidget *typeradiobtn3;
  GtkWidget *typeradiobtn2;
  GtkWidget *label22;
  GtkWidget *dialog_action_area2;
  GtkWidget *newfeedbtn;
  GtkWidget *cancelbtn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  newdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (newdialog), _("New Entry"));
  gtk_window_set_position (GTK_WINDOW (newdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (newdialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (newdialog), 400, -1);

  dialog_vbox2 = GTK_DIALOG (newdialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox9, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  label5 = gtk_label_new (_("feed URL"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox1), label5, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label5), 5, 0);

  newfeedentry = gtk_entry_new ();
  gtk_widget_show (newfeedentry);
  gtk_box_pack_start (GTK_BOX (hbox1), newfeedentry, TRUE, TRUE, 0);

  vbox12 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (vbox9), vbox12, FALSE, FALSE, 5);
  gtk_container_set_border_width (GTK_CONTAINER (vbox12), 5);

  frame5 = gtk_frame_new (NULL);
  gtk_widget_show (frame5);
  gtk_box_pack_start (GTK_BOX (vbox12), frame5, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (frame5), hbox11);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 5);

  typeradiobtn = gtk_radio_button_new_with_mnemonic (NULL, _("RSS"));
  gtk_widget_show (typeradiobtn);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, typeradiobtn, _("select this type to subscribe to a RDF/RSS feed"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (typeradiobtn), TRUE);

  typeradiobtn1 = gtk_radio_button_new_with_mnemonic (NULL, _("CDF"));
  gtk_widget_show (typeradiobtn1);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn1, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, typeradiobtn1, _("select this type to subscribe to a CDF feed (the feed type used by MSIE)"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn1), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn1));

  typeradiobtn3 = gtk_radio_button_new_with_mnemonic (NULL, _("Atom/Echo/PIE"));
  gtk_widget_show (typeradiobtn3);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn3, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, typeradiobtn3, _("select this type if you want to subscribe to a Atom/Echo/PIE 0.2 feed"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn3), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn3));

  typeradiobtn2 = gtk_radio_button_new_with_mnemonic (NULL, _("OCS Directory"));
  gtk_widget_show (typeradiobtn2);
  gtk_box_pack_start (GTK_BOX (hbox11), typeradiobtn2, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, typeradiobtn2, _("select this type to subscribe to a OCS directory"), NULL);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (typeradiobtn2), typeradiobtn_group);
  typeradiobtn_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (typeradiobtn2));

  label22 = gtk_label_new (_("feed type"));
  gtk_widget_show (label22);
  gtk_frame_set_label_widget (GTK_FRAME (frame5), label22);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label22), 5, 0);

  dialog_action_area2 = GTK_DIALOG (newdialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  newfeedbtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (newfeedbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (newdialog), newfeedbtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (newfeedbtn, GTK_CAN_DEFAULT);

  cancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (newdialog), cancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) newdialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newdialog));
  g_signal_connect_swapped ((gpointer) newfeedbtn, "clicked",
                            G_CALLBACK (on_newfeedbtn_clicked),
                            GTK_OBJECT (newfeedentry));
  g_signal_connect_data ((gpointer) newfeedbtn, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (newdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) cancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, newdialog, "newdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (newdialog, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (newdialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (newdialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (newdialog, newfeedentry, "newfeedentry");
  GLADE_HOOKUP_OBJECT (newdialog, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (newdialog, frame5, "frame5");
  GLADE_HOOKUP_OBJECT (newdialog, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn, "typeradiobtn");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn1, "typeradiobtn1");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn3, "typeradiobtn3");
  GLADE_HOOKUP_OBJECT (newdialog, typeradiobtn2, "typeradiobtn2");
  GLADE_HOOKUP_OBJECT (newdialog, label22, "label22");
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (newdialog, newfeedbtn, "newfeedbtn");
  GLADE_HOOKUP_OBJECT (newdialog, cancelbtn, "cancelbtn");
  GLADE_HOOKUP_OBJECT_NO_REF (newdialog, tooltips, "tooltips");

  return newdialog;
}

GtkWidget*
create_feednamedialog (void)
{
  GtkWidget *feednamedialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox6;
  GtkWidget *hbox2;
  GtkWidget *feedname;
  GtkWidget *feednameentry;
  GtkWidget *hbox7;
  GtkWidget *label17;
  GtkObject *feedrefreshcount_adj;
  GtkWidget *feedrefreshcount;
  GtkWidget *dialog_action_area4;
  GtkWidget *okbutton4;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  feednamedialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (feednamedialog), _("Entry Name"));
  gtk_window_set_position (GTK_WINDOW (feednamedialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (feednamedialog), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (feednamedialog), 400, -1);

  dialog_vbox4 = GTK_DIALOG (feednamedialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox6, TRUE, TRUE, 0);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  feedname = gtk_label_new (_("feed name"));
  gtk_widget_show (feedname);
  gtk_box_pack_start (GTK_BOX (hbox2), feedname, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (feedname), GTK_JUSTIFY_LEFT);

  feednameentry = gtk_entry_new ();
  gtk_widget_show (feednameentry);
  gtk_box_pack_start (GTK_BOX (hbox2), feednameentry, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feednameentry, _("either leave the name supplied by the feed or enter an alternative name which you like to be listed in the feed list"), NULL);

  hbox7 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox7, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox7), 5);

  label17 = gtk_label_new (_("feed refresh interval (in minutes)"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_LEFT);

  feedrefreshcount_adj = gtk_adjustment_new (0, 0, 100000, 5, 10, 10);
  feedrefreshcount = gtk_spin_button_new (GTK_ADJUSTMENT (feedrefreshcount_adj), 1, 0);
  gtk_widget_show (feedrefreshcount);
  gtk_box_pack_start (GTK_BOX (hbox7), feedrefreshcount, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, feedrefreshcount, _("Please remember to set a reasonable refresh time, its not useful to poll daily updated feeds every 15 minutes! To disable auto-updating the feed set the interval to 0."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (feedrefreshcount), TRUE);

  dialog_action_area4 = GTK_DIALOG (feednamedialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  okbutton4 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton4);
  gtk_dialog_add_action_widget (GTK_DIALOG (feednamedialog), okbutton4, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton4, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) feednamedialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (feednamedialog));
  g_signal_connect_swapped ((gpointer) okbutton4, "clicked",
                            G_CALLBACK (on_feednamebutton_clicked),
                            GTK_OBJECT (feednameentry));
  g_signal_connect_data ((gpointer) okbutton4, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (feednamedialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, feednamedialog, "feednamedialog");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (feednamedialog, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (feednamedialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (feednamedialog, feedname, "feedname");
  GLADE_HOOKUP_OBJECT (feednamedialog, feednameentry, "feednameentry");
  GLADE_HOOKUP_OBJECT (feednamedialog, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (feednamedialog, label17, "label17");
  GLADE_HOOKUP_OBJECT (feednamedialog, feedrefreshcount, "feedrefreshcount");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (feednamedialog, okbutton4, "okbutton4");
  GLADE_HOOKUP_OBJECT_NO_REF (feednamedialog, tooltips, "tooltips");

  return feednamedialog;
}

GtkWidget*
create_prefdialog (void)
{
  GtkWidget *prefdialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *vbox3;
  GtkWidget *frame2;
  GtkWidget *vbox14;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *hbox14;
  GtkWidget *radiobutton2;
  GtkWidget *browsercmd;
  GtkWidget *label13;
  GtkWidget *frame6;
  GtkWidget *vbox15;
  GtkWidget *timeradiobtn1;
  GSList *timeradiobtn1_group = NULL;
  GtkWidget *timeradiobtn2;
  GtkWidget *hbox15;
  GtkWidget *timeradiobtn3;
  GtkWidget *timeformatentry;
  GtkWidget *label24;
  GtkWidget *dialog_action_area5;
  GtkWidget *prefsavebtn;
  GtkWidget *prefcancelbtn;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  prefdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (prefdialog), _("program preferences"));
  gtk_window_set_position (GTK_WINDOW (prefdialog), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (prefdialog), 300, -1);

  dialog_vbox5 = GTK_DIALOG (prefdialog)->vbox;
  gtk_widget_show (dialog_vbox5);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), vbox3, FALSE, TRUE, 2);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, TRUE, TRUE, 0);

  vbox14 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox14);
  gtk_container_add (GTK_CONTAINER (frame2), vbox14);
  gtk_container_set_border_width (GTK_CONTAINER (vbox14), 5);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("use the GNOME default browser"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (vbox14), radiobutton1, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (radiobutton1, FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  hbox14 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox14), hbox14, TRUE, TRUE, 0);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("use browser command"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox14), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton2), TRUE);

  browsercmd = gtk_entry_new ();
  gtk_widget_show (browsercmd);
  gtk_box_pack_start (GTK_BOX (hbox14), browsercmd, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, browsercmd, _("specify a browser command using %s as URL placeholder"), NULL);

  label13 = gtk_label_new (_("browser settings"));
  gtk_widget_show (label13);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label13);
  gtk_label_set_justify (GTK_LABEL (label13), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label13), 5, 0);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox3), frame6, TRUE, TRUE, 0);

  vbox15 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox15);
  gtk_container_add (GTK_CONTAINER (frame6), vbox15);
  gtk_container_set_border_width (GTK_CONTAINER (vbox15), 5);

  timeradiobtn1 = gtk_radio_button_new_with_mnemonic (NULL, _("display only time"));
  gtk_widget_show (timeradiobtn1);
  gtk_box_pack_start (GTK_BOX (vbox15), timeradiobtn1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (timeradiobtn1), timeradiobtn1_group);
  timeradiobtn1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (timeradiobtn1));

  timeradiobtn2 = gtk_radio_button_new_with_mnemonic (NULL, _("display date and time"));
  gtk_widget_show (timeradiobtn2);
  gtk_box_pack_start (GTK_BOX (vbox15), timeradiobtn2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (timeradiobtn2), timeradiobtn1_group);
  timeradiobtn1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (timeradiobtn2));

  hbox15 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox15), hbox15, TRUE, TRUE, 0);

  timeradiobtn3 = gtk_radio_button_new_with_mnemonic (NULL, _("user defined format"));
  gtk_widget_show (timeradiobtn3);
  gtk_box_pack_start (GTK_BOX (hbox15), timeradiobtn3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (timeradiobtn3), timeradiobtn1_group);
  timeradiobtn1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (timeradiobtn3));

  timeformatentry = gtk_entry_new ();
  gtk_widget_show (timeformatentry);
  gtk_box_pack_start (GTK_BOX (hbox15), timeformatentry, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, timeformatentry, _("for expert users: specify a time format string, consult the strftime() manpage for the format codes"), NULL);

  label24 = gtk_label_new (_("date column settings"));
  gtk_widget_show (label24);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), label24);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_LEFT);
  gtk_misc_set_padding (GTK_MISC (label24), 5, 0);

  dialog_action_area5 = GTK_DIALOG (prefdialog)->action_area;
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_END);

  prefsavebtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (prefsavebtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdialog), prefsavebtn, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (prefsavebtn, GTK_CAN_DEFAULT);

  prefcancelbtn = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (prefcancelbtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (prefdialog), prefcancelbtn, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (prefcancelbtn, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) prefdialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (prefdialog));
  g_signal_connect ((gpointer) prefsavebtn, "clicked",
                    G_CALLBACK (on_prefsavebtn_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) prefcancelbtn, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (prefdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, prefdialog, "prefdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, dialog_vbox5, "dialog_vbox5");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (prefdialog, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (prefdialog, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (prefdialog, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (prefdialog, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (prefdialog, browsercmd, "browsercmd");
  GLADE_HOOKUP_OBJECT (prefdialog, label13, "label13");
  GLADE_HOOKUP_OBJECT (prefdialog, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (prefdialog, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (prefdialog, timeradiobtn1, "timeradiobtn1");
  GLADE_HOOKUP_OBJECT (prefdialog, timeradiobtn2, "timeradiobtn2");
  GLADE_HOOKUP_OBJECT (prefdialog, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (prefdialog, timeradiobtn3, "timeradiobtn3");
  GLADE_HOOKUP_OBJECT (prefdialog, timeformatentry, "timeformatentry");
  GLADE_HOOKUP_OBJECT (prefdialog, label24, "label24");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, dialog_action_area5, "dialog_action_area5");
  GLADE_HOOKUP_OBJECT (prefdialog, prefsavebtn, "prefsavebtn");
  GLADE_HOOKUP_OBJECT (prefdialog, prefcancelbtn, "prefcancelbtn");
  GLADE_HOOKUP_OBJECT_NO_REF (prefdialog, tooltips, "tooltips");

  return prefdialog;
}

GtkWidget*
create_newfolderdialog (void)
{
  GtkWidget *newfolderdialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *vbox10;
  GtkWidget *hbox12;
  GtkWidget *label20;
  GtkWidget *foldertitleentry;
  GtkWidget *dialog_action_area6;
  GtkWidget *button2;
  GtkWidget *button3;

  newfolderdialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (newfolderdialog), _("add folder"));
  gtk_window_set_modal (GTK_WINDOW (newfolderdialog), TRUE);

  dialog_vbox6 = GTK_DIALOG (newfolderdialog)->vbox;
  gtk_widget_show (dialog_vbox6);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), vbox10, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox12);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox12, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox12), 5);

  label20 = gtk_label_new (_("folder name"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox12), label20, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);

  foldertitleentry = gtk_entry_new ();
  gtk_widget_show (foldertitleentry);
  gtk_box_pack_start (GTK_BOX (hbox12), foldertitleentry, TRUE, TRUE, 0);

  dialog_action_area6 = GTK_DIALOG (newfolderdialog)->action_area;
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_END);

  button2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (newfolderdialog), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  button3 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button3);
  gtk_dialog_add_action_widget (GTK_DIALOG (newfolderdialog), button3, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) newfolderdialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newfolderdialog));
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_newfolderbtn_clicked),
                    NULL);
  g_signal_connect_data ((gpointer) button2, "clicked",
                         G_CALLBACK (gtk_widget_hide),
                         GTK_OBJECT (newfolderdialog),
                         NULL, G_CONNECT_AFTER | G_CONNECT_SWAPPED);
  g_signal_connect_swapped ((gpointer) button3, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (newfolderdialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, newfolderdialog, "newfolderdialog");
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, dialog_vbox6, "dialog_vbox6");
  GLADE_HOOKUP_OBJECT (newfolderdialog, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (newfolderdialog, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (newfolderdialog, label20, "label20");
  GLADE_HOOKUP_OBJECT (newfolderdialog, foldertitleentry, "foldertitleentry");
  GLADE_HOOKUP_OBJECT_NO_REF (newfolderdialog, dialog_action_area6, "dialog_action_area6");
  GLADE_HOOKUP_OBJECT (newfolderdialog, button2, "button2");
  GLADE_HOOKUP_OBJECT (newfolderdialog, button3, "button3");

  return newfolderdialog;
}

GtkWidget*
create_foldernamedialog (void)
{
  GtkWidget *foldernamedialog;
  GtkWidget *dialog_vbox7;
  GtkWidget *hbox13;
  GtkWidget *label23;
  GtkWidget *foldernameentry;
  GtkWidget *dialog_action_area7;
  GtkWidget *foldernamechangebtn;
  GtkWidget *cancelbutton1;

  foldernamedialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (foldernamedialog), _("edit folder name"));
  gtk_window_set_modal (GTK_WINDOW (foldernamedialog), TRUE);

  dialog_vbox7 = GTK_DIALOG (foldernamedialog)->vbox;
  gtk_widget_show (dialog_vbox7);

  hbox13 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (dialog_vbox7), hbox13, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox13), 5);

  label23 = gtk_label_new (_("folder name"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox13), label23, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_LEFT);

  foldernameentry = gtk_entry_new ();
  gtk_widget_show (foldernameentry);
  gtk_box_pack_start (GTK_BOX (hbox13), foldernameentry, TRUE, TRUE, 0);

  dialog_action_area7 = GTK_DIALOG (foldernamedialog)->action_area;
  gtk_widget_show (dialog_action_area7);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area7), GTK_BUTTONBOX_END);

  foldernamechangebtn = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (foldernamechangebtn);
  gtk_dialog_add_action_widget (GTK_DIALOG (foldernamedialog), foldernamechangebtn, 0);
  GTK_WIDGET_SET_FLAGS (foldernamechangebtn, GTK_CAN_DEFAULT);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (foldernamedialog), cancelbutton1, 0);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  g_signal_connect_swapped ((gpointer) foldernamedialog, "delete_event",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (foldernamedialog));
  g_signal_connect ((gpointer) foldernamechangebtn, "clicked",
                    G_CALLBACK (on_foldernamechangebtn_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) cancelbutton1, "clicked",
                            G_CALLBACK (gtk_widget_hide),
                            GTK_OBJECT (foldernamedialog));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (foldernamedialog, foldernamedialog, "foldernamedialog");
  GLADE_HOOKUP_OBJECT_NO_REF (foldernamedialog, dialog_vbox7, "dialog_vbox7");
  GLADE_HOOKUP_OBJECT (foldernamedialog, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (foldernamedialog, label23, "label23");
  GLADE_HOOKUP_OBJECT (foldernamedialog, foldernameentry, "foldernameentry");
  GLADE_HOOKUP_OBJECT_NO_REF (foldernamedialog, dialog_action_area7, "dialog_action_area7");
  GLADE_HOOKUP_OBJECT (foldernamedialog, foldernamechangebtn, "foldernamechangebtn");
  GLADE_HOOKUP_OBJECT (foldernamedialog, cancelbutton1, "cancelbutton1");

  return foldernamedialog;
}

