/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_propdialog (void);
GtkWidget* create_newdialog (void);
GtkWidget* create_prefdialog (void);
GtkWidget* create_newfolderdialog (void);
GtkWidget* create_foldernamedialog (void);
GtkWidget* create_fileselection (void);
GtkWidget* create_filterdialog (void);
GtkWidget* create_ruledialog (void);
GtkWidget* create_feedsterdialog (void);
GtkWidget* create_importdialog (void);
GtkWidget* create_exportdialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_authdialog (void);
GtkWidget* create_window1 (void);
